### PR TITLE
[breaking] Update ember cli 3.28

### PR DESCRIPTION
**Pull request by jrjohnson**
A few things in this update made for a lot of churn. 
1) The move to prettier
2) More lint assertions in tests
3) Adding embroider support

I left everything in individual commits as I figured that would be easier to review. Let me know if you want me to squash them.

This is a *breaking* change as it drops support for Node <12.

### CODE REVIEW

**Comment by jrjohnson** [comment]
Just checking in @fivetanley to see if you'd like to see any changes here. Trying to clear up some deprecations about the version of `ember-cli-babel` used before this update.

**Comment by fivetanley** [comment]
@jrjohnson thanks for this! I pulled this into a branch added support for node 16 in the test CI workflow in https://github.com/fivetanley/ember-promise-helpers/pull/143, but otherwise I took all of your commits from this PR. thanks for taking the time to make this change! I'll have a new release out shortly

**Comment by fivetanley** [comment]
@jrjohnson ember-promise-helpers@2.0.0 is out! thanks for your help!

**Comment by jrjohnson** [comment]
Awesome, thanks!

**Pull request merged**
