### PR TITLE
Support 1..n promises

### PR DESCRIPTION
**Pull request by josex2r**
Hi, I want to make a proposal to extend the functionality of this addon.

To wait for `n` promises to render something in the templates I have to create a computed property to make an `Ember.RSVP.all` with the promises, but in some cases I prefer to write some logic in the templates.

I know this unneccessary if I create a computed property grouping all the promises, but maybe can be interesting to have a helper that does the job.

I've created a proxy helper, `are-pending`, to allow passing an Array of promises or `1..n` promises to the `is-pending` helper.

### CODE REVIEW

**Comment by fivetanley** [comment]
Hey jose,

sorry for the late response! What do you think about exposing a `promise-all` helper instead?

The implementation would follow the rest of them, but use Promise.all instead. This would allow all of the helpers `(is-rejected, await, is-pending, etc) to work without adding a separate `are-pending`, `await-all`, etc for each individual method.

**Comment by josex2r** [comment]
Nice, I think it's a better solution 👍 
I'll modify this pull so I do not have to create another one.

**Comment by fivetanley** [comment]
Hmmm, I am not sure why Travis is failing.

**Comment by josex2r** [comment]
I think there is something wrong with the version of the `ember-try` package.

Should I update the travis script?
I could try to upgrade the files with the data of an addon generated with the last `ember-cli`version.

**Comment by fivetanley** [comment]
Hey Jose,

Sorry for the long delay. This looks great! Can you remove yarn.lock and I'll merge?

**Comment by josex2r** [comment]
Hi, I think it's ready :)

**Pull request merged**
